# -*- coding: utf-8 -*-
"""Yt_Chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QNkqF7oP_-h6Ad6K-y1hFJNwrQgMSGAT
"""

import os
from google.colab import userdata
# Securely pull your API key from Colab's left sidebar (🔑 icon)
os.environ["GEMINI_API_KEY"] = userdata.get('GEMINI_API_KEY')
os.environ["HF_TOKEN"] = userdata.get('HF_TOKEN')

!pip install -q youtube-transcript-api langchain-community langchain-google-genai langchain-text-splitters faiss-cpu tiktoken python-dotenv

!pip install -q langchain-classic

!pip install -q langchain-huggingface
from youtube_transcript_api import YouTubeTranscriptApi, TranscriptsDisabled
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_google_genai import GoogleGenerativeAIEmbeddings, ChatGoogleGenerativeAI
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_core.prompts import PromptTemplate

"""# **Step 1a - Indexing (Document Ingestion)**"""

from youtube_transcript_api import YouTubeTranscriptApi, TranscriptsDisabled

video_id = "Gfr50f6ZBvo"

try:
    # 1. Instantiate the API client
    ytt_api = YouTubeTranscriptApi()

    # 2. Execute the network request and store the object
    fetched_transcript = ytt_api.fetch(video_id, languages=['en'])

    # 3. Convert the typed object into raw dictionary data
    transcript_list = fetched_transcript.to_raw_data()

    # 4. Parse and flatten the text chunks
    transcript = " ".join(chunk["text"] for chunk in transcript_list)

    # 5. Output the final string
    print(transcript)

except TranscriptsDisabled:
    print("No captions available for this video")

"""# **Step 1B - Indexing (Text Splitting)**"""

splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=200)
chunks = splitter.create_documents([transcript])

"""# **Step 1c & 1d - Indexing (Embedding Generation and Storing in Vector Store)**"""

embeddings = HuggingFaceEmbeddings(model_name="BAAI/bge-small-en-v1.5")
vector_store = FAISS.from_documents(chunks, embeddings)

vector_store.index_to_docstore_id

"""# **Step2 - Retrival**"""

retriever = vector_store.as_retriever(search_type="similarity", search_kwargs={"k":4})

retriever

retriever.invoke("what is deepmind")

"""# **Step 3 - Augmentation**"""

llm = ChatGoogleGenerativeAI(model= 'gemini-3-flash-preview', temperature=0.2)

prompt = PromptTemplate(
    template="""
      You are a helpful assistant.
      Answer ONLY from the provided transcript context.
      If the context is insufficient, just say you dont know.

      {context}
      Question: {question}
      """,
    input_variables = ['context', 'question']
)

question = "is the topic of aliens discussed in this video? if yes then what was discussed"
retrieved_docs = retriever.invoke(question)

context_text = "\n\n".join(doc.page_content for doc in retrieved_docs)
context_text

final_prompt = prompt.invoke({"context": context_text, "question": question})

final_prompt

"""# **Step 4 - Generation**"""

answer = llm.invoke(final_prompt)
print((answer.content))

"""# **Building a Chain**"""

from langchain_core.runnables import RunnableParallel, RunnablePassthrough, RunnableLambda
from langchain_core.output_parsers import StrOutputParser

def format_docs(retrieved_docs):
  context_text = "\n\n".join(doc.page_content for doc in retrieved_docs)
  return context_text

parallel_chain = RunnableParallel({
    'context': retriever | RunnableLambda(format_docs),
    'question':RunnablePassthrough()
})

parallel_chain.invoke('who is Demis')

parser = StrOutputParser()

main_chain = parallel_chain | prompt | llm | parser

main_chain.invoke('Can you summarize the video')